const RIC_WHOAMI_TYPE_CODE_ADDON_DISTANCE = "VCNL4200";
const RIC_WHOAMI_TYPE_CODE_ADDON_LIGHT = "lightsensor";
const RIC_WHOAMI_TYPE_CODE_ADDON_COLOUR = "coloursensor";
const RIC_WHOAMI_TYPE_CODE_ADDON_IRFOOT = "IRFoot";
const RIC_WHOAMI_TYPE_CODE_ADDON_LEDFOOT = "LEDfoot";
const RIC_WHOAMI_TYPE_CODE_ADDON_LEDARM = "LEDarm";
const RIC_WHOAMI_TYPE_CODE_ADDON_LEDEYE = "LEDeye";
const RIC_WHOAMI_TYPE_CODE_ADDON_NOISE = "noisesensor";
const RIC_WHOAMI_TYPE_CODE_ADDON_GRIPSERVO = "roboservo3";

const EXCLUDED_ADDONS = [
  RIC_WHOAMI_TYPE_CODE_ADDON_LEDFOOT,
  RIC_WHOAMI_TYPE_CODE_ADDON_LEDARM,
  RIC_WHOAMI_TYPE_CODE_ADDON_LEDEYE,
  RIC_WHOAMI_TYPE_CODE_ADDON_GRIPSERVO,
];
export default EXCLUDED_ADDONS;
