name: 'Build and Publish to NPM'

on:
  release:
    types: [created]

jobs:
  build-publish:
    environment: NPM_TOKEN_NIK
    runs-on: ubuntu-latest

    steps:
      - name: checking repository out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: .

      - name: Use Node.js '16.x'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: installing npm dependencies
        run: npm install
      
      - name: build web app
        run: npm run build:webapp
      
      - name: build phone app
        run: npm run build

      - name: publishing to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
